### ISSUE TITLE
Naming Issue

### ISSUE THREAD

**Issue by TheCrazyGM** [robinvandernoord/uvx2#2]
The base uv tool now has a tool-runner called uvx (which caused all kinds of issues when i just ran `uvx upgrade-all` so, might need to rethink something. I had to revert back to pipx in the mean time.
![image](https://github.com/robinvandernoord/uvx/assets/20504480/c0bb9d86-c3e7-4749-9c33-5c13e4d02db7)

**Comment by robinvandernoord** [comment]
I just updated uv to the latest version and replicated this issue. After reinstalling `uvx` it did work again, but of course a name collision with an official `uv` tool is not great. 

I'll have to think about a new name then, I guess. Any ideas?
- uvy
- uvirt
- uvenv
- ?

**Comment by TheCrazyGM** [comment]
First ones that came to mind were uvy or uvz, although uvenv does make sense in a way.

**Comment by robinvandernoord** [comment]
Thank you for your feedback. I've settled on `uvenv` as it best describes what this library is.
I've claimed the name on pypi and will transition to this name soon.
Once this is done, I'll close this issue.

**Comment by robinvandernoord** [comment]
I've published [Release 3.0](https://github.com/robinvandernoord/uvenv/releases/tag/3.0.0) with the new name, which is also available on [pypi.org/project/uvenv](https://pypi.org/project/uvenv/).

In addition, I have released update 2.5 for `uvx`, which will show a deprecation warning, and running `self update` from that version will move the user to `uvenv`. The latest `uvx` code has been archived in [a new branch with the same name](https://github.com/robinvandernoord/uvenv/tree/uvx).

In order to migrate existing virtual environments, `uvenv self migrate` can be used.
For more information, see the release notes.
